// packages/react/src/components/group.tsx
import { PropsWithChildren, useContext, useMemo } from 'react'
import type { ClipRectParams } from '@maxxam0n/canvasify-core'

import { GroupContext } from '../contexts/group-context'
import { TransformGroup } from './transform'

export interface GroupProps extends PropsWithChildren {
	x?: number
	y?: number
	opacity?: number
	zIndex?: number
	/** Clip в локальных координатах группы (после translate). */
	clipRect?: Omit<ClipRectParams, 'type'>
}

export const Group = ({
	x = 0,
	y = 0,
	opacity = 1,
	zIndex = 0,
	clipRect,
	children,
}: GroupProps) => {
	const inherited = useContext(GroupContext)

	const groupParams = useMemo(() => {
		return {
			opacity: opacity * (inherited?.opacity ?? 1),
			zIndex: zIndex + (inherited?.zIndex ?? 0),
		}
	}, [opacity, zIndex, inherited])

	return (
		<GroupContext.Provider value={groupParams}>
			<TransformGroup
				translate={{
					translateX: x,
					translateY: y,
				}}
				clipRect={clipRect}
			>
				{children}
			</TransformGroup>
		</GroupContext.Provider>
	)
}

// packages/vue/src/ui/Group.vue
<template>
	<Transform :translate="{ translateX: x, translateY: y }" :clip-rect="clipRect">
		<slot />
	</Transform>
</template>

<script lang="ts" setup>
import type { ComputedRef } from 'vue'
import { computed, inject, provide } from 'vue'
import type { ClipRectParams, GroupParams } from '@maxxam0n/canvasify-core'

import { CANVAS_TOKENS } from '../lib/tokens'

import Transform from './Transform.vue'

export interface GroupProps {
	x?: number
	y?: number
	opacity?: number
	zIndex?: number
	clipRect?: Omit<ClipRectParams, 'type'>
}

const props = withDefaults(defineProps<GroupProps>(), {
	x: 0,
	y: 0,
	opacity: 1,
	zIndex: 0,
	clipRect: undefined,
})

const parentGroupParams = inject<ComputedRef<GroupParams>>(
	CANVAS_TOKENS.GROUP,
	computed(() => ({ opacity: 1, zIndex: 0 })),
)

const groupParams = computed<GroupParams>(() => ({
	opacity: props.opacity * (parentGroupParams?.value.opacity ?? 1),
	zIndex: props.zIndex + (parentGroupParams?.value.zIndex ?? 0),
}))

provide(CANVAS_TOKENS.GROUP, groupParams)
</script>
