// packages/react/src/components/layer.tsx
import {
	CSSProperties,
	PropsWithChildren,
	useCallback,
	useContext,
	useEffect,
	useMemo,
	useState,
} from 'react'
import {
	Layer as CoreLayer,
	RenderLayer,
	type LayerWorkerRendererOptions,
	type SpatialIndexOptions,
} from '@maxxam0n/canvasify-core'

import { CanvasContext } from '../contexts/canvas-context'
import { CanvasSizeContext } from '../contexts/canvas-size-context'
import { LayerContext } from '../contexts/layer-context'

export interface LayerProps extends PropsWithChildren {
	name: string
	opacity?: number
	zIndex?: number
	renderer?: RenderLayer
	/** Передаётся в конструктор Core Layer; смена prop пересоздаёт слой. */
	spatialIndex?: SpatialIndexOptions
	/**
	 * Experimental: paint в worker через OffscreenCanvas.
	 * Смена prop пересоздаёт слой — держите стабильную ссылку на createWorker / port.
	 */
	workerRenderer?: LayerWorkerRendererOptions
}

export const Layer = ({
	name,
	children,
	renderer,
	opacity = 1,
	zIndex = 0,
	spatialIndex,
	workerRenderer,
}: LayerProps) => {
	const canvas = useContext(CanvasContext)
	const size = useContext(CanvasSizeContext)
	const [layer, setLayer] = useState<CoreLayer | null>(null)
	const [canvasElement, setCanvasElement] = useState<HTMLCanvasElement | null>(null)

	if (!canvas) {
		throw new Error('failed to register layer: canvas not found')
	}

	const refCallback = useCallback((node: HTMLCanvasElement | null) => {
		setCanvasElement(node)
	}, [])

	useEffect(() => {
		if (!canvasElement || !canvas) return

		const nextLayer = new CoreLayer({
			name,
			canvas: canvasElement,
			opacity,
			zIndex,
			spatialIndex,
			workerRenderer,
			onDirty: () => canvas.requestRender(),
		})

		canvas.deleteLayer(name).setLayer(nextLayer)
		setLayer(nextLayer)

		return () => {
			canvas.deleteLayer(name)
			setLayer(null)
		}
	}, [canvas, canvasElement, name, spatialIndex, workerRenderer])

	useEffect(() => {
		if (!layer || !size) return
		layer.setSize(size.width, size.height)
	}, [layer, size])

	useEffect(() => {
		if (!layer) return
		layer.setOpacity(opacity)
	}, [layer, opacity])

	useEffect(() => {
		if (!layer) return
		layer.setZIndex(zIndex)
	}, [layer, zIndex])

	useEffect(() => {
		if (!layer || workerRenderer) return
		layer.setRenderer(renderer)
	}, [layer, renderer, workerRenderer])

	const style: CSSProperties = useMemo(
		() => ({
			zIndex,
			position: 'absolute',
			top: 0,
			left: 0,
		}),
		[zIndex],
	)

	return (
		<LayerContext.Provider value={layer}>
			<canvas ref={refCallback} style={style} />
			{children}
		</LayerContext.Provider>
	)
}

// packages/vue/src/ui/Layer.vue
<template>
	<canvas ref="canvasRef" class="absolute left-0 top-0" :style="{ zIndex }" />
	<slot />
</template>

<script setup lang="ts">
import type { ComputedRef, Ref } from 'vue'
import { inject, provide, shallowRef, useTemplateRef, watch } from 'vue'
import { Layer } from '@maxxam0n/canvasify-core'
import type {
	Canvas,
	LayerWorkerRendererOptions,
	RenderLayer,
	SpatialIndexOptions,
} from '@maxxam0n/canvasify-core'

import { CANVAS_TOKENS } from '../lib/tokens'

export interface LayerProps {
	name: string
	opacity?: number
	zIndex?: number
	renderer?: RenderLayer
	/** Передаётся в конструктор Core Layer; смена prop пересоздаёт слой. */
	spatialIndex?: SpatialIndexOptions
	/**
	 * Experimental: paint в worker через OffscreenCanvas.
	 * Смена prop пересоздаёт слой — держите стабильную ссылку на createWorker / port.
	 */
	workerRenderer?: LayerWorkerRendererOptions
}

const props = withDefaults(defineProps<LayerProps>(), {
	opacity: 1,
	zIndex: 0,
	renderer: undefined,
	spatialIndex: undefined,
	workerRenderer: undefined,
})

const canvas = inject<Canvas>(CANVAS_TOKENS.CANVAS)
const width = inject<ComputedRef<number>>(CANVAS_TOKENS.WIDTH)
const height = inject<ComputedRef<number>>(CANVAS_TOKENS.HEIGHT)

const canvasRef = useTemplateRef('canvasRef')
const layer = shallowRef<Layer | null>(null) as Ref<Layer | null>

provide(CANVAS_TOKENS.LAYER, layer)

// Создаём Layer при появлении canvas-элемента; пересоздаём при смене name / spatialIndex / workerRenderer
watch(
	[canvasRef, () => props.name, () => props.spatialIndex, () => props.workerRenderer],
	([el], _prev, onCleanup) => {
		if (!el || !canvas || !width || !height) return

		const nextLayer = new Layer({
			name: props.name,
			canvas: el,
			opacity: props.opacity,
			zIndex: props.zIndex,
			spatialIndex: props.spatialIndex,
			workerRenderer: props.workerRenderer,
			onDirty: () => canvas.requestRender(),
		})
		nextLayer.setSize(width.value, height.value)
		if (!props.workerRenderer) {
			nextLayer.setRenderer(props.renderer)
		}

		canvas.deleteLayer(props.name).setLayer(nextLayer)
		layer.value = nextLayer

		onCleanup(() => {
			canvas.deleteLayer(props.name)
			if (layer.value === nextLayer) {
				layer.value = null
			}
		})
	},
	{ immediate: true },
)

watch(
	[() => width?.value, () => height?.value],
	([w, h]) => {
		if (layer.value && typeof w === 'number' && typeof h === 'number') {
			layer.value.setSize(w, h)
		}
	},
)

watch(
	() => props.opacity,
	opacity => {
		layer.value?.setOpacity(opacity)
	},
)

watch(
	() => props.zIndex,
	zIndex => {
		layer.value?.setZIndex(zIndex)
	},
)

watch(
	() => props.renderer,
	renderer => {
		if (props.workerRenderer) return
		layer.value?.setRenderer(renderer)
	},
)

defineExpose({
	getCore: () => layer.value,
})
</script>
