// packages/react/src/components/transform.tsx
import { PropsWithChildren, useContext, useMemo } from 'react'
import type {
	ClipRectParams,
	MatrixParams,
	RotationParams,
	ScaleParams,
	SkewParams,
	Transform,
	TranslateParams,
} from '@maxxam0n/canvasify-core'

import { TransformContext } from '../contexts/transform-context'

export interface TransformGroupProps extends PropsWithChildren {
	translate?: Omit<TranslateParams, 'type'>
	scale?: Omit<ScaleParams, 'type'>
	rotate?: Omit<RotationParams, 'type'>
	skew?: Omit<SkewParams, 'type'>
	matrix?: Omit<MatrixParams, 'type'>
	clipRect?: Omit<ClipRectParams, 'type'>
}

export const TransformGroup = ({
	translate,
	scale,
	rotate,
	skew,
	matrix,
	clipRect,
	children,
}: TransformGroupProps) => {
	const parentTransforms = useContext(TransformContext)

	const localTransforms = useMemo<Transform[]>(() => {
		const transforms: Transform[] = []

		if (translate) {
			transforms.push({ type: 'translate', ...translate })
		}
		if (scale) {
			transforms.push({ type: 'scale', ...scale })
		}
		if (rotate) {
			transforms.push({ type: 'rotation', ...rotate })
		}
		if (skew) {
			transforms.push({ type: 'skew', ...skew })
		}
		if (matrix) {
			transforms.push({ type: 'matrix', ...matrix })
		}
		if (clipRect) {
			transforms.push({ type: 'clip-rect', ...clipRect })
		}

		return transforms
	}, [translate, scale, rotate, skew, matrix, clipRect])

	const transforms = useMemo<Transform[]>(() => {
		return [...parentTransforms, ...localTransforms]
	}, [parentTransforms, localTransforms])

	return <TransformContext.Provider value={transforms}>{children}</TransformContext.Provider>
}

// packages/vue/src/ui/Transform.vue
<template>
	<slot />
</template>

<script lang="ts" setup>
import type { ComputedRef } from 'vue'
import { computed, inject, provide, toValue } from 'vue'
import type {
	Transform,
	RotationParams,
	ScaleParams,
	SkewParams,
	MatrixParams,
	TranslateParams,
	ClipRectParams,
} from '@maxxam0n/canvasify-core'

import { CANVAS_TOKENS } from '../lib/tokens'

export interface TransformProps {
	translate?: Omit<TranslateParams, 'type'>
	scale?: Omit<ScaleParams, 'type'>
	rotate?: Omit<RotationParams, 'type'>
	skew?: Omit<SkewParams, 'type'>
	matrix?: Omit<MatrixParams, 'type'>
	clipRect?: Omit<ClipRectParams, 'type'>
}

const props = defineProps<TransformProps>()

const parentTransforms = inject<ComputedRef<Transform[]>>(
	CANVAS_TOKENS.TRANSFORMS,
	computed(() => []),
)

const localTransforms = computed<Transform[]>(() => {
	const { translate, scale, rotate, skew, matrix, clipRect } = props
	const transforms: Transform[] = []

	if (translate) transforms.push({ type: 'translate', ...translate })
	if (scale) transforms.push({ type: 'scale', ...scale })
	if (rotate) transforms.push({ type: 'rotation', ...rotate })
	if (skew) transforms.push({ type: 'skew', ...skew })
	if (matrix) transforms.push({ type: 'matrix', ...matrix })
	if (clipRect) transforms.push({ type: 'clip-rect', ...clipRect })

	return transforms
})

const combinedTransforms = computed<Transform[]>(() => {
	const parent = parentTransforms ? toValue(parentTransforms) : []

	return [...parent, ...toValue(localTransforms)]
})

provide(CANVAS_TOKENS.TRANSFORMS, combinedTransforms)
</script>
